---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: nfs-app
spec:
  containers:
    - name: app
      image: public.ecr.aws/docker/library/centos:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"      
      securityContext:
        allowPrivilegeEscalation: false  # modify this depending on your use case    
        readOnlyRootFilesystem: true # modify this depending on your use case
      volumeMounts:
        - name: persistent-storage
          mountPath: /data               
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: nfs-claim
